/*
 * This source file was generated by the Gradle 'init' task
 */
package lab_2.task;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        System.out.println("Enter a string:");
        String inputStr = in.nextLine();
        in.close();

        System.out.println("You've printed following string: " + inputStr);

        // Example usage of countWords
        StringBuilder text = new StringBuilder(inputStr);
        StringBuilder searchWords = new StringBuilder("Hello world test");
        System.out.println("\nWord occurrences:");
        StringOperation.countWords(text, searchWords);

        // Example usage of switchFirstLastWord
        System.out.println("\nSwitch first and last word:");
        StringOperation.switchFirstLastWord(text);
    }
}
